# Generated by Django 3.0.4 on 2020-09-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200314_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_urls',
            name='short_url',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
